// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaKmVsWyebMWDea9Oo2JSPtUTPFeDjwrU',
    appId: '1:855858480512:web:910378f8e5672ca7066d65',
    messagingSenderId: '855858480512',
    projectId: 'cs-interview-e548a',
    authDomain: 'cs-interview-e548a.firebaseapp.com',
    storageBucket: 'cs-interview-e548a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrNg5L31bO9KFC_FQYHfHV4BJW8VmoswM',
    appId: '1:855858480512:android:0be09d27725742ad066d65',
    messagingSenderId: '855858480512',
    projectId: 'cs-interview-e548a',
    storageBucket: 'cs-interview-e548a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gmSdEKdJkFGYRxZ14G6uBXnQzsamBGU',
    appId: '1:855858480512:ios:cd0c571bb9b12071066d65',
    messagingSenderId: '855858480512',
    projectId: 'cs-interview-e548a',
    storageBucket: 'cs-interview-e548a.firebasestorage.app',
    iosClientId: '855858480512-6e92842chapfkbq7vgslbgmf0tnqs2q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0gmSdEKdJkFGYRxZ14G6uBXnQzsamBGU',
    appId: '1:855858480512:ios:cd0c571bb9b12071066d65',
    messagingSenderId: '855858480512',
    projectId: 'cs-interview-e548a',
    storageBucket: 'cs-interview-e548a.firebasestorage.app',
    iosClientId: '855858480512-6e92842chapfkbq7vgslbgmf0tnqs2q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaKmVsWyebMWDea9Oo2JSPtUTPFeDjwrU',
    appId: '1:855858480512:web:b47723fe399799c7066d65',
    messagingSenderId: '855858480512',
    projectId: 'cs-interview-e548a',
    authDomain: 'cs-interview-e548a.firebaseapp.com',
    storageBucket: 'cs-interview-e548a.firebasestorage.app',
  );
}
